// client_solid/src/components/Shell.tsx
// Shell.tsx — sidebar + topbar shell (Solid.js port of poc/components/shell.jsx)
//
// P2-2: nav-item を <A href> 化。
//   - <A> が <a> を描画するため、middle-click / Cmd+click / 新しいタブ が効く。
//   - setRoute は keyboard shortcut 経由では残す (prop として受ける)。
//   - 実際のナビゲーションは <A> が router.navigate を呼ぶので setRoute は不要。
//
// P4-20: ルート遷移で毎回 .fade-enter をリトリガー。
//   - <main> に static で付いている .fade-enter は初回マウント時しか発火しない。
//   - useLocation().pathname を watch し、変わったタイミングで class を一度外して
//     強制 reflow 後に再付与することで CSS アニメーションを再生する。
import { createEffect, For, Show, type JSX } from "solid-js";
import { A, useLocation } from "@solidjs/router";
import { type RouteKey } from "../data";
import { getCurrentUser } from "../api";
import { Icons } from "./Icons";
import { BottomTabBar } from "./BottomTabBar";
import { Breadcrumb, type Crumb } from "./Breadcrumb";
import { ROUTE_PATHS, sidebarRouteKey } from "../router";
import { openCommandPalette } from "../store/commandPalette";
import { getThemeMode, toggleNightRed } from "../store/theme";

interface NavEntry {
  key: RouteKey;
  label: string;
  icon: () => JSX.Element;
  group: "EC" | "飼育" | "取引" | "運営";
  /** 動的な数値として評価される。0 や undefined の場合はバッジを表示しない */
  badge?: () => number | undefined;
  hidden?: boolean;
}

const GROUPS: Array<NavEntry["group"]> = ["EC", "飼育", "取引", "運営"];

interface ShellProps {
  current: RouteKey;
  setRoute: (r: RouteKey) => void;
  /** P2-14: パンくずは構造化した Crumb[] で渡す (JSX ではない) */
  crumbs: Crumb[];
  children: JSX.Element;
  topActions?: JSX.Element;
  /** カート内の合計点数 */
  cartCount?: () => number;
  /** 60 日以内に羽化予定の個体数 */
  eclosionCount?: () => number;
}

export const Shell = (props: ShellProps) => {
  // P4-20: route 変更で <main> の fade アニメを再生する
  const location = useLocation();
  let mainRef: HTMLElement | undefined;
  let prevPath: string | null = null;
  createEffect(() => {
    const path = location.pathname;
    if (!mainRef) {
      prevPath = path;
      return;
    }
    if (prevPath !== null && prevPath !== path) {
      mainRef.classList.remove("fade-enter");
      // reflow を強制して animation を確実にリスタートさせる
      void mainRef.offsetWidth;
      mainRef.classList.add("fade-enter");
    }
    prevPath = path;
  });

  const nav: NavEntry[] = [
    { key: "products", label: "生体・用品", icon: Icons.grid, group: "EC" },
    { key: "product-detail", label: "商品詳細", icon: Icons.tag, group: "EC", hidden: true },
    {
      key: "cart",
      label: "カート",
      icon: Icons.cart,
      group: "EC",
      badge: () => props.cartCount?.(),
    },
    { key: "mypage", label: "マイページ", icon: Icons.home, group: "飼育" },
    // 個体カルテは詳細ビュー (`:id` パラメトリック) なので、サイドバーには出さない。
    // マイページの所有個体カード / 羽化レーダー / Bloodline 等から id 付きで開く。
    { key: "specimen", label: "個体カルテ", icon: Icons.card, group: "飼育", hidden: true },
    { key: "log", label: "飼育ログ", icon: Icons.timeline, group: "飼育" },
    {
      key: "eclosion",
      label: "羽化予測",
      icon: Icons.bell,
      group: "飼育",
      badge: () => props.eclosionCount?.(),
    },
    { key: "bloodline", label: "血統系図", icon: Icons.tree, group: "飼育" },
    { key: "market", label: "C2Cマーケット", icon: Icons.beetle, group: "取引" },
    { key: "shop", label: "ショップ管理", icon: Icons.shop, group: "運営" },
  ];

  return (
    <div class="app">
      <aside class="sidebar" role="navigation" aria-label="メインナビゲーション">
        <div class="brand">
          <div class="brand-mark" aria-hidden="true">
            蟲
          </div>
          <div>
            <div class="brand-name">KOCHŪ</div>
            <div class="brand-sub">昆虫EC × 飼育ログ</div>
          </div>
        </div>

        <For each={GROUPS}>
          {(g) => (
            <div class="nav-group">
              <div class="nav-title">{g}</div>
              <For each={nav.filter((n) => n.group === g && !n.hidden)}>
                {(n) => {
                  // UX-1: 詳細ビュー (specimen / product-detail) は親ルートの子として扱う。
                  //   個体カルテ表示中もサイドバー上ではマイページを active にする。
                  const isActive = () => sidebarRouteKey(props.current) === n.key;
                  const badgeVal = () => n.badge?.();
                  return (
                    <A
                      href={ROUTE_PATHS[n.key]}
                      class={"nav-item" + (isActive() ? " active" : "")}
                      aria-current={isActive() ? "page" : undefined}
                    >
                      {n.icon()}
                      <span>{n.label}</span>
                      <Show when={badgeVal() && badgeVal()! > 0}>
                        <span class="nav-badge" aria-label={`${n.label} ${badgeVal()} 件`}>
                          {badgeVal()}
                        </span>
                      </Show>
                    </A>
                  );
                }}
              </For>
            </div>
          )}
        </For>

        <div class="sidebar-footer">
          <div class="avatar" aria-hidden="true">
            {getCurrentUser().initial}
          </div>
          <div>
            <div class="user-name">{getCurrentUser().name}</div>
            <div class="user-role">{getCurrentUser().role}</div>
          </div>
        </div>
      </aside>

      <div class="main">
        <header class="topbar">
          <Breadcrumb items={props.crumbs} />
          {/* P4-5: 擬似検索バー — クリックで CommandPalette を開く (input ではなく button) */}
          <button
            type="button"
            class="search search-trigger"
            aria-label="検索 (Command+K)"
            onClick={openCommandPalette}
          >
            <svg
              class="sicon"
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              aria-hidden="true"
            >
              <circle cx="11" cy="11" r="7" />
              <path d="M20 20l-4-4" />
            </svg>
            <span class="search-placeholder">
              個体ID・種名・商品を検索...
            </span>
            <span class="kbd skbd" aria-hidden="true">
              ⌘K
            </span>
          </button>
          {/* P4-8: 夜間赤色テーマ トグル */}
          <button
            type="button"
            class={
              "theme-toggle" +
              (getThemeMode() === "night-red" ? " is-active" : "")
            }
            onClick={toggleNightRed}
            aria-pressed={getThemeMode() === "night-red"}
            aria-label={
              getThemeMode() === "night-red"
                ? "夜間赤色モードをオフ"
                : "夜間赤色モードをオン"
            }
            title={
              getThemeMode() === "night-red"
                ? "夜間赤色モード: オン"
                : "夜間赤色モード: オフ (自動)"
            }
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="1.7"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z" />
            </svg>
          </button>
          {props.topActions}
        </header>
        <main
          class="content fade-enter"
          role="main"
          ref={(el) => (mainRef = el)}
        >
          {props.children}
        </main>
      </div>

      {/* モバイル下部タブ — desktop/tablet では CSS で非表示 */}
      <BottomTabBar
        current={props.current}
        setRoute={props.setRoute}
        cartCount={props.cartCount}
        eclosionCount={props.eclosionCount}
      />
    </div>
  );
};

// poc/components/shell.jsx
// shell.jsx — sidebar + topbar shell
const { useState, useEffect, useMemo, useRef } = React;

const Shell = ({ current, setRoute, children, crumb, topActions }) => {
  const nav = [
    { key: "products", label: "生体・用品", icon: Icons.grid, group: "EC" },
    { key: "product-detail", label: "商品詳細", icon: Icons.tag, group: "EC", hidden: true },
    { key: "cart", label: "カート", icon: Icons.cart, group: "EC", badge: "2" },
    { key: "mypage", label: "マイページ", icon: Icons.home, group: "飼育" },
    { key: "specimen", label: "個体カルテ", icon: Icons.card, group: "飼育" },
    { key: "log", label: "飼育ログ", icon: Icons.timeline, group: "飼育" },
    { key: "eclosion", label: "羽化予測", icon: Icons.bell, group: "飼育", badge: "3" },
    { key: "bloodline", label: "血統系図", icon: Icons.tree, group: "飼育" },
    { key: "market", label: "C2Cマーケット", icon: Icons.beetle, group: "取引" },
    { key: "shop", label: "ショップ管理", icon: Icons.shop, group: "運営" },
  ];

  const groups = ["EC", "飼育", "取引", "運営"];

  return (
    <div className="app">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark">蟲</div>
          <div>
            <div className="brand-name">KOCHŪ</div>
            <div className="brand-sub">昆虫EC × CARE LOG</div>
          </div>
        </div>

        {groups.map(g => (
          <div className="nav-group" key={g}>
            <div className="nav-title">{g}</div>
            {nav.filter(n => n.group === g && !n.hidden).map(n => (
              <div
                key={n.key}
                className={"nav-item" + (current === n.key ? " active" : "")}
                onClick={() => setRoute(n.key)}
              >
                {n.icon}
                <span>{n.label}</span>
                {n.badge && <span className="nav-badge">{n.badge}</span>}
              </div>
            ))}
          </div>
        ))}

        <div className="sidebar-footer">
          <div className="avatar">{APP_DATA.user.initial}</div>
          <div>
            <div className="user-name">{APP_DATA.user.name}</div>
            <div className="user-role">{APP_DATA.user.role}</div>
          </div>
        </div>
      </aside>

      <div className="main">
        <header className="topbar">
          <div className="crumb">{crumb}</div>
          <div className="search">
            <svg className="sicon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="7" /><path d="M20 20l-4-4" /></svg>
            <input placeholder="個体ID・種名・商品を検索" />
            <span className="kbd skbd">⌘K</span>
          </div>
          {topActions}
        </header>
        <main className="content fade-enter" key={current}>
          {children}
        </main>
      </div>
    </div>
  );
};

window.Shell = Shell;
